AB-557 : Open Edition NFT contract
Anotherblock/contracts-v2 pull request #14
Opened 2023-09-27 08:08 UTC by 0xPilou

2023-10-02 08:42 UTC, 0xPilou commented
updated PR : 
Merge dev branch containing ERC721AB base abstract contract

ERC721ABOE updates : reduce to only mint and initDrop method

2023-10-02 08:58 UTC, jonathangus approved these changes

2023-10-02 09:05 UTC, jonathangus requested changes

2023-10-02 09:05 UTC, jonathangus commented on src/token/ERC721/ERC721ABOE.sol
> +        if (mintedPerPhase[_to][_phaseId] + _quantity > phase.maxMint) revert ABErrors.MAX_MINT_PER_ADDRESS();
should we still have this?

2023-10-03 11:01 UTC, 0xPilou commented on src/token/ERC721/ERC721ABOE.sol
> +        if (mintedPerPhase[_to][_phaseId] + _quantity > phase.maxMint) revert ABErrors.MAX_MINT_PER_ADDRESS();
removed the `MAX_MINT` check on mint

2023-10-03 11:06 UTC, jonathangus approved these changes

2023-10-09 07:25 UTC, merged